# Generated by Django 3.2 on 2022-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20221027_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_room',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ManyToManyField(to='chat.User'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='allowed_users',
            field=models.IntegerField(default=2),
        ),
    ]
